SpaceData/FastQuery/urls.py
from django.urls import path
from . import views

app_name = 'FastQuery'

urlpatterns = [

    path('', views.DashboardView.as_view(), name = 'Dashboard'),
    path('dataset', views.DatasetView.as_view(), name = 'Dataset'),
    path('download', views.DownloadView.as_view(), name = 'Download'),
    path('query', views.QueryView.as_view(), name = 'Query'),
    path('query1', views.Query1View.as_view(), name = 'Query1'),
    path('query2', views.Query2View.as_view(), name = 'Query2'),
    path('query3', views.Query3View.as_view(), name = 'Query3'),
    path('naive', views.NaiveView.as_view(), name = 'Naive'),

]

SpaceData/SpaceData/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('FastQuery.urls')),

]

SpaceData/FastQuery/models.py
from django.db import models

# Create your models here.

SpaceData/FastQuery/forms.py
from django import forms

class Query1Form(forms.Form):
    x = forms.FloatField(required = True)
    y = forms.FloatField(required = True)
    z = forms.FloatField(required = True)

class Query2Form(forms.Form):
    x = forms.FloatField(required = True)
    y = forms.FloatField(required = True)
    z = forms.FloatField(required = True)
    radius = forms.FloatField(required = True)

class Query3Form(forms.Form):
    x = forms.FloatField(required = True)
    y = forms.FloatField(required = True)
    z = forms.FloatField(required = True)

SpaceData/FastQuery/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from . import forms
from django.views.static import serve
from django.views import View
from . import utils
import os
import time

from FastQuery import generic, query1, query2, query3
from SpaceData.wsgi import star_info, cube_info, neighbour_info
from FastQuery.datatype import Star, Cube, StarInfo

def keyfunction(star):
    return star.distance

class DashboardView(View):
    template_name = 'FastQuery/home.html'

    def get(self, request):
        return render(request, self.template_name)

class DatasetView(View):
    template_name = 'FastQuery/dataset.html'

    def get(self, request):
        files = utils.list_files()
        return render(request, self.template_name, {'files': files})

class DownloadView(View):
    template_name = 'FastQuery/dataset.html'

    def get(self, request):
        filename = request.GET.get('file')
        if filename:
            if filename == 'compressed.zip':
                file = utils.get_file(filename)
                response = HttpResponse(file, content_type = 'compressed/zip')
                response['Content-Disposition'] = 'attachment; filename=' + filename
                return response
            else:
                file = utils.get_file(filename)
                response = HttpResponse(file, content_type = 'text/plain')
                response['Content-Disposition'] = 'attachment; filename=' + filename
                return response

class QueryView(View):
    template_name = 'FastQuery/query.html'

    def get(self, request):
        return render(request, self.template_name)

class Query1View(View):
    template_name = 'FastQuery/query1.html'

    def get(self, request):
        form = forms.Query1Form()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = forms.Query1Form(request.POST)
        if form.is_valid():
            x = float(form.cleaned_data.get('x'))
            y = float(form.cleaned_data.get('y'))
            z = float(form.cleaned_data.get('z'))
            cube = generic.get_cube_id(x, y, z)
            if cube == Cube(-1, -1, -1, -1):
                return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Cube dimension not supported'})

            if 'list' not in request.POST:
                start_time = time.time()
                ans1, ans2 = query1.count(cube)
                end_time = time.time()
                return render(request, self.template_name, {'form': form, 'ans1': ans1, 'ans2': ans2, 'total': ans1 + ans2, 'time': end_time - start_time})

            elif 'list' in request.POST:
                start_time = time.time()
                ans1, ans2, L = query1.list_stars(cube, x, y, z)
                end_time = time.time()
                return render(request, self.template_name, {'form': form, 'ans1': ans1, 'ans2': ans2, 'total': ans1 + ans2, 'list': L, 'time': end_time - start_time})
        else:
            return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Invalid Submission'})

class Query2View(View):
    template_name = 'FastQuery/query2.html'

    def get(self, request):
        form = forms.Query2Form()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = forms.Query2Form(request.POST)
        if form.is_valid():
            x = float(form.cleaned_data.get('x'))
            y = float(form.cleaned_data.get('y'))
            z = float(form.cleaned_data.get('z'))
            cube = generic.get_cube_id(x, y, z)
            if cube == Cube(-1, -1, -1, -1):
                return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Cube dimension not supported'})

            start_time = time.time()
            stars = query2.BFS(cube, x, y, z, float(form.cleaned_data.get('radius')))
            end_time = time.time()

            # D = {}
            # S = []
            #
            # for star in stars:
            #     if star not in D:
            #         D[star] = 1
            #         S.append(star)
            #
            # S = sorted(S, key=keyfunction)

            if 'list' not in request.POST:
                return render(request, self.template_name, {'form': form, 'stars': len(stars), 'time': end_time - start_time})

            elif 'list' in request.POST:
                return render(request, self.template_name, {'form': form, 'stars': len(stars), 'list': stars, 'time': end_time - start_time})
        else:
            return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Invalid Submission'})

class Query3View(View):
    template_name = 'FastQuery/query3.html'

    def get(self, request):
        form = forms.Query3Form()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = forms.Query3Form(request.POST)
        if form.is_valid():
            x = float(form.cleaned_data.get('x'))
            y = float(form.cleaned_data.get('y'))
            z = float(form.cleaned_data.get('z'))
            cube = generic.get_cube_id(x, y, z)
            if cube == Cube(-1, -1, -1, -1):
                return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Cube dimension not supported'})

            start_time = time.time()
            stars = query3.find_spiral_arm(cube, x, y, z)
            end_time = time.time()

            return render(request, self.template_name, {'form': form, 'stars': len(stars), 'list': stars, 'time': end_time - start_time})
        
        else:
            return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Invalid Submission'})

class NaiveView(View):
    template_name = 'FastQuery/naive.html'

    def get(self, request):
        form = forms.Query2Form()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = forms.Query2Form(request.POST)
        if form.is_valid():
            x = float(form.cleaned_data.get('x'))
            y = float(form.cleaned_data.get('y'))
            z = float(form.cleaned_data.get('z'))
            cube = generic.get_cube_id(x, y, z)
            if cube == Cube(-1, -1, -1, -1):
                return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Cube dimension not supported'})

            start_time = time.time()
            stars = query2.naive(cube, x, y, z, float(form.cleaned_data.get('radius')))
            end_time = time.time()

            if 'list' not in request.POST:
                return render(request, self.template_name, {'form': form, 'stars': len(stars), 'time': end_time - start_time})

            elif 'list' in request.POST:
                return render(request, self.template_name, {'form': form, 'stars': len(stars), 'list': stars, 'time': end_time - start_time})
        else:
            return render(request, self.template_name, {'form': form, 'err': 1, 'msg': 'Invalid Submission'})

SpaceData/FastQuery/templates/FastQuery/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>FastQuery</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="img/favicon.png" rel="icon">
  <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Roboto:100,300,400,500,700|Philosopher:400,400i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

  <!-- Bootstrap css -->
  <!-- <link rel="stylesheet" href="css/bootstrap.css"> -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/modal-video/css/modal-video.min.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

  <header id="header" class="header header-hide">
    <div class="container">

      <div id="logo" class="pull-left">
        <h1><a href="{% url 'FastQuery:Dashboard' %}" style="font-size: 30px;" class="scrollto"><span>Fast</span>Query</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="#body"><img src="img/logo.png" alt="" title="" /></a>-->
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li {% block homeblock %}{% endblock %}><a href="{% url 'FastQuery:Dashboard' %}" style="font-size: 18px;">Home</a></li>
          <li {% block datasetblock %}{% endblock %}><a href="{% url 'FastQuery:Dataset' %}" style="font-size: 18px;">Dataset</a></li>
          <li {% block queryblock %}{% endblock %}><a href="{% url 'FastQuery:Query' %}" style="font-size: 18px;">Query</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->

  {% block content %}{% endblock %}

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/modal-video/js/modal-video.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'lib/wow/wow.min.js' %}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>

    <style>
        html {
            overflow-y: scroll;
        }
    </style>

</body>

SpaceData/FastQuery/templates/FastQuery/dataset.html
{% extends 'FastQuery/base.html' %}

{% block datasetblock %} class="menu-active" {% endblock %}

{% block content %}

    <section id="features" class="padd-section text-center" style="margin-top: 2%;">
        <div class="container border border-light rounded">
            <div style="margin-top: 2%;">
                <div class="section-title text-center">
                    <h2><strong>DATASET</strong></h2>

                    <p class="separator" style="font-size: 20px;">Manipulated Data - <b>Open Sourced</b></p>
                </div>
            </div>

            <table class="table table-striped border rounded">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">File</th>
                        <th scope="col">Size</th>
                        <th scope="col">Download</th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in files %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ file.filename }}</td>
                            <td>{{ file.filesize }} MB</td>
                            <td><a href="{% url 'FastQuery:Download' %}?file={{ file.filename }}">Download</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </section>

{% endblock %}

SpaceData/FastQuery/templates/FastQuery/home.html
{% extends 'FastQuery/base.html' %}

{% block homeblock %} class="menu-active" {% endblock %}

{% block content %}

    <section id="hero" class="wow fadeIn">
        <div class="hero-container">
            <h1>You have just found FastQuery</h1>
            <h2>Manipulated Gaia-Tycho-2 Data</h2>
            <a href="{% url 'FastQuery:Query' %}" class="btn-get-started scrollto">Get Started</a>
            <div class="btns">
                <a href="{% url 'FastQuery:Dataset' %}"><i style="font-size: 20px;" class="fas fa-cloud-download-alt"></i> &nbsp; Dataset</a>
                <a href="https://github.com/dumbape" target="_blank"><i style="font-size: 20px;" class="fab fa-github"></i> &nbsp; Github</a>
            </div>
        </div>
    </section>

{% endblock %}

SpaceData/FastQuery/templates/FastQuery/instructions.html
{% extends 'FastQuery/base.html' %}

{% block instructionsblock %} class="menu-active" {% endblock %}

{% block content %}

    <section id="features" class="padd-section text-center" style="margin-top: 2%;">
        <div class="container border border-light rounded">
            <div style="margin-top: 2%;">
                <div class="section-title text-center">
                    <h2><strong>INSTRUCTIONS</strong></h2>
                    <p class="separator" style="font-size: 20px;">The hybrid Data Structure, explained</p>
                </div>
            </div>

        </div>
    </section>

{% endblock %}

SpaceData/FastQuery/templates/FastQuery/naive.html
{% extends 'FastQuery/base.html' %}
{% load widget_tweaks %}

{% block queryblock %} class="menu-active" {% endblock %}

{% block content %}

    <section id="features" class="padd-section text-center" style="margin-top: 2%;">
        <div class="container border border-light rounded">
            <div style="margin-top: 2%;">
                <div class="section-title text-center">
                    <h2><strong>NAIVE METHOD</strong></h2>
                    <p class="separator" style="font-size: 20px;">Stars within a distance</p>
                </div>
            </div>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col">

                        <form method="POST">
                            {% csrf_token %}
                              <div class="form-row">
                                <div class="form-group col-md-3">
                                  {% render_field form.x type="number" class="form-control" Placeholder="X Coordinate" %}
                                </div>
                                <div class="form-group col-md-3">
                                  {% render_field form.y type="number" class="form-control" Placeholder="Y Coordinate" %}
                                </div>
                                <div class="form-group col-md-3">
                                  {% render_field form.z type="number" class="form-control" Placeholder="Z Coordinate" %}
                                </div>
                                <div class="form-group col-md-3">
                                  {% render_field form.radius type="number" class="form-control" Placeholder="Radius" %}
                                </div>
                              </div>
                              <div class="form-group form-check mx-sm-3 mb-2">
                                  <input type="checkbox" name="list" value="list" class="form-check-input">
                                  <label class="form-check-label">List Stars</label>
                              </div>
                              <button type="submit" class="btn btn-info mb-2">Query!</button>
                        </form>

                    </div>
                </div>
            </div>

            {% if err %}

                <div class="alert alert-danger" style="margin-top: 5%;">
                    {{ msg }}
                </div>

            {% else %}

            {% if request.POST %}

                {% if list %}

                    <div class="alert alert-info" style="margin-top: 5%;">
                        Number of Stars Found: &nbsp; <strong style="font-size: 18px;">{{ stars }}</strong>
                    </div>
                    <div class="alert alert-light" style="margin-top: 2%;">
                        Processing Time Taken (sec): &nbsp; <strong style="font-size: 18px;">{{ time }}</strong>
                    </div>

                    <div class="container" style="margin-top: 2%;">

                        <table class="table table-striped border rounded">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Coordinate</th>
                                    <th scope="col">Distance</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for star in list %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ star.X }}, {{ star.Y }}, {{ star.Z }}</td>
                                        <td>{{ star.distance }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>

                {% else %}

                <div class="alert alert-info" style="margin-top: 5%;">
                    Number of Stars Found: &nbsp; <strong style="font-size: 18px;">{{ stars }}</strong>
                </div>
                <div class="alert alert-light" style="margin-top: 2%;">
                    Processing Time Taken (sec): &nbsp; <strong style="font-size: 18px;">{{ time }}</strong>
                </div>

                {% endif %}

            {% endif %}

            {% endif %}



        </div>
    </section>

{% endblock %}

SpaceData/FastQuery/templates/FastQuery/query.html
{% extends 'FastQuery/base.html' %}

{% block queryblock %} class="menu-active" {% endblock %}

{% block content %}

    <div class="container" style="margin-top: 2%;">

        <section id="get-started" class="padd-section text-center" style="margin-top: 2%;">

        <div class="container">
          <div class="section-title text-center">

            <h2><b>Query</b></h2>
            <p class="separator" style="font-size: 20px;">Experience FastQuery</p>

          </div>
        </div>

        <div class="container">
          <div class="row">

            <div class="col-md-6 col-lg-4">
              <div class="feature-block">

                <h4 style="font-size: 22px;">Query 1</h4>
                <p style="font-size: 18px;">Neighbourhood of a Data Cube</p>
                <a class="btn btn-light" href="{% url 'FastQuery:Query1' %}" style="font-size: 18px;">Check Out</a>

              </div>
            </div>

            <div class="col-md-6 col-lg-4">
              <div class="feature-block">

                <h4 style="font-size: 22px;">Query 2</h4>
                <p style="font-size: 18px;">Stars within a distance</p>
                <a class="btn btn-light" href="{% url 'FastQuery:Query2' %}" style="font-size: 18px;">Check Out</a>

              </div>
            </div>

            <div class="col-md-6 col-lg-4">
              <div class="feature-block">

                <h4 style="font-size: 22px;">Query 3</h4>
                <p style="font-size: 18px;">Spiral Arm of the Galaxy</p>
                <a class="btn btn-light" href="{% url 'FastQuery:Query3' %}" style="font-size: 18px;">Check Out</a>

              </div>
            </div>

          </div>
        </div>

      </section>


    </div>



{% endblock %}

SpaceData/FastQuery/templates/FastQuery/query1.html
{% extends 'FastQuery/base.html' %}
{% load widget_tweaks %}

{% block queryblock %} class="menu-active" {% endblock %}

{% block content %}

    <section id="features" class="padd-section text-center" style="margin-top: 2%;">
        <div class="container border border-light rounded">
            <div style="margin-top: 2%;">
                <div class="section-title text-center">
                    <h2><strong>QUERY 1</strong></h2>
                    <p class="separator" style="font-size: 20px;">Neighbourhood of a Data Cube</p>
                </div>
            </div>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col">
                        <form method="POST" class="form-inline">
                            {% csrf_token %}
                            <div class="form-group mb-2">
                              {% render_field form.x type="number" class="form-control" Placeholder="X Coordinate (ly)" %}
                            </div>
                            <div class="form-group mx-sm-3 mb-2">
                              {% render_field form.y type="number" class="form-control" Placeholder="Y Coordinate (ly)" %}
                            </div>
                            <div class="form-group mx-sm-3 mb-2">
                              {% render_field form.z type="number" class="form-control" Placeholder="Z Coordinate (ly)" %}
                            </div>
                            <div class="form-group form-check mx-sm-3 mb-2">
                                <input type="checkbox" name="list" value="list" class="form-check-input">
                                <label class="form-check-label">List Stars</label>
                            </div>
                            <button type="submit" class="btn btn-info mb-2">Query!</button>
                        </form>
                    </div>
                </div>
            </div>

            {% if err %}

                <div class="alert alert-danger" style="margin-top: 5%;">
                    {{ msg }}
                </div>

            {% else %}

            {% if request.POST %}

                {% if list %}

                    <div class="alert alert-info" style="margin-top: 5%;">
                        Number of Stars in Self Cube: &nbsp; <strong style="font-size: 18px;">{{ ans1 }}</strong>
                    </div>
                    <div class="alert alert-info" style="margin-top: 2%;">
                        Number of Stars in Neighbouring Cubes: &nbsp; <strong style="font-size: 18px;">{{ ans2 }}</strong>
                    </div>
                    <div class="alert alert-info" style="margin-top: 2%;">
                        Total Stars in Neighbourhood: &nbsp; <strong style="font-size: 18px;">{{ total }}</strong>
                    </div>
                    <div class="alert alert-light" style="margin-top: 2%;">
                        Processing Time Taken (sec): &nbsp; <strong style="font-size: 18px;">{{ time }}</strong>
                    </div>

                    <div class="container" style="margin-top: 2%;">

                        <table class="table table-striped border rounded">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Coordinate</th>
                                    <th scope="col">Location</th>
                                    <th scope="col">Distance</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for star in list %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ star.X }}, {{ star.Y }}, {{ star.Z }}</td>
                                        <td>{{ star.location }}</td>
                                        <td>{{ star.distance }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>

                {% else %}

                <div class="alert alert-info" style="margin-top: 5%;">
                    Number of Stars in Self Cube: &nbsp; <strong style="font-size: 18px;">{{ ans1 }}</strong>
                </div>
                <div class="alert alert-info" style="margin-top: 2%;">
                    Number of Stars in Neighbouring Cubes: &nbsp; <strong style="font-size: 18px;">{{ ans2 }}</strong>
                </div>
                <div class="alert alert-info" style="margin-top: 2%;">
                    Total Stars in Neighbourhood: &nbsp; <strong style="font-size: 18px;">{{ total }}</strong>
                </div>
                <div class="alert alert-light" style="margin-top: 2%;">
                    Processing Time Taken (sec): &nbsp; <strong style="font-size: 18px;">{{ time }}</strong>
                </div>

                {% endif %}

            {% endif %}

            {% endif %}



        </div>
    </section>

{% endblock %}

SpaceData/FastQuery/templates/FastQuery/query2.html
{% extends 'FastQuery/base.html' %}
{% load widget_tweaks %}

{% block queryblock %} class="menu-active" {% endblock %}

{% block content %}

    <section id="features" class="padd-section text-center" style="margin-top: 2%;">
        <div class="container border border-light rounded">
            <div style="margin-top: 2%;">
                <div class="section-title text-center">
                    <h2><strong>QUERY 2</strong></h2>
                    <p class="separator" style="font-size: 20px;">Stars within a distance</p>
                </div>
            </div>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col">

                        <form method="POST">
                            {% csrf_token %}
                              <div class="form-row">
                                <div class="form-group col-md-3">
                                  {% render_field form.x type="number" class="form-control" Placeholder="X Coordinate (ly)" %}
                                </div>
                                <div class="form-group col-md-3">
                                  {% render_field form.y type="number" class="form-control" Placeholder="Y Coordinate (ly)" %}
                                </div>
                                <div class="form-group col-md-3">
                                  {% render_field form.z type="number" class="form-control" Placeholder="Z Coordinate (ly)" %}
                                </div>
                                <div class="form-group col-md-3">
                                  {% render_field form.radius type="number" class="form-control" Placeholder="Radius (ly)" %}
                                </div>
                              </div>
                              <div class="form-group form-check mx-sm-3 mb-2">
                                  <input type="checkbox" name="list" value="list" class="form-check-input">
                                  <label class="form-check-label">List Stars</label>
                              </div>
                              <button type="submit" class="btn btn-info mb-2">Query!</button>
                        </form>

                    </div>
                </div>
            </div>

            {% if err %}

                <div class="alert alert-danger" style="margin-top: 5%;">
                    {{ msg }}
                </div>

            {% else %}

            {% if request.POST %}

                {% if list %}

                    <div class="alert alert-info" style="margin-top: 5%;">
                        Number of Stars Found: &nbsp; <strong style="font-size: 18px;">{{ stars }}</strong>
                    </div>
                    <div class="alert alert-light" style="margin-top: 2%;">
                        Processing Time Taken (sec): &nbsp; <strong style="font-size: 18px;">{{ time }}</strong>
                    </div>

                    <div class="container" style="margin-top: 2%;">

                        <table class="table table-striped border rounded">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Coordinate</th>
                                    <th scope="col">Distance</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for star in list %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ star.X }}, {{ star.Y }}, {{ star.Z }}</td>
                                        <td>{{ star.distance }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>

                {% else %}

                <div class="alert alert-info" style="margin-top: 5%;">
                    Number of Stars Found: &nbsp; <strong style="font-size: 18px;">{{ stars }}</strong>
                </div>
                <div class="alert alert-light" style="margin-top: 2%;">
                    Processing Time Taken (sec): &nbsp; <strong style="font-size: 18px;">{{ time }}</strong>
                </div>

                {% endif %}

            {% endif %}

            {% endif %}



        </div>
    </section>

{% endblock %}